CREATE TABLE "ACT_CPT_PX_2018AA_HPDS_MAP" 
   (	"ACT_C_FULLNAME" VARCHAR2(700 BYTE), 
    "OMOP_S_CONCEPT_ID" NUMBER,
    "OMOP_NS_CONCEPT_ID" NUMBER,
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_BASECODE" VARCHAR2(100 BYTE), 
	"HPDS_PATH" VARCHAR2(4000 BYTE)
   );
CREATE TABLE "ACT_ICD10CM_DX_2018AA_HPDS_MAP" 
   (	"ACT_C_FULLNAME" VARCHAR2(700 BYTE), 
    "OMOP_S_CONCEPT_ID" NUMBER,
    "OMOP_NS_CONCEPT_ID" NUMBER,
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_BASECODE" VARCHAR2(100 BYTE), 
	"HPDS_PATH" VARCHAR2(4000 BYTE)
   );
CREATE TABLE "ACT_MED_ALPHA_HPDS_MAP" 
   (	"ACT_C_FULLNAME" VARCHAR2(700 BYTE), 
    "OMOP_S_CONCEPT_ID" NUMBER,
    "OMOP_NS_CONCEPT_ID" NUMBER, 
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_BASECODE" VARCHAR2(100 BYTE), 
	"HPDS_PATH" VARCHAR2(4000 BYTE)
   );
CREATE TABLE "NCATS_DEMOGRAPHICS_HPDS_MAP" 
   (	"ACT_C_FULLNAME" VARCHAR2(700 BYTE), 
    "OMOP_S_CONCEPT_ID" NUMBER,
    "OMOP_NS_CONCEPT_ID" NUMBER,
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_BASECODE" VARCHAR2(100 BYTE), 
	"HPDS_PATH" VARCHAR2(4000 BYTE)
   );
CREATE TABLE "NCATS_LABS_HPDS_MAP" 
   (	"ACT_C_FULLNAME" VARCHAR2(700 BYTE), 
    "OMOP_S_CONCEPT_ID" NUMBER,
    "OMOP_NS_CONCEPT_ID" NUMBER,
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_BASECODE" VARCHAR2(100 BYTE), 
	"HPDS_PATH" VARCHAR2(4000 BYTE)
   );
CREATE TABLE "NCATS_VISIT_DETAILS_HPDS_MAP" 
   (	"ACT_C_FULLNAME" VARCHAR2(700 BYTE), 
    "OMOP_S_CONCEPT_ID" NUMBER,
    "OMOP_NS_CONCEPT_ID" NUMBER,
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_BASECODE" VARCHAR2(100 BYTE), 
	"HPDS_PATH" VARCHAR2(4000 BYTE)
   );
   
CREATE TABLE "ACT_COVID_HPDS_MAP" 
   (	"ACT_C_FULLNAME" VARCHAR2(700 BYTE), 
    "OMOP_S_CONCEPT_ID" NUMBER,
    "OMOP_NS_CONCEPT_ID" NUMBER,
	"C_NAME" VARCHAR2(2000 BYTE), 
	"C_BASECODE" VARCHAR2(100 BYTE), 
	"HPDS_PATH" VARCHAR2(4000 BYTE)
   );
 