--New table creation and initial data load script

/*
--New tables created for the ACT load.
TM_CZ.A_NCATS_DEMOGRAPHICS 
TM_CZ.A_NCATS_VISIT_DETAILS 
TM_CZ.A_ACT_ICD10PCS_PX_2018AA_MAP 
TM_CZ.A_NCATS_ICD10_ICD9_DX_V1_MAP 
TM_CZ.HPDS_DATA_LATEST 


--i2b2TM tables should already exist, and TM_CZ user should have select permissions on these tables.

I2B2DEMODATA.PATIENT_DIMENSION
I2B2DEMODATA.OBSERVATION_FACT 
I2B2DEMODATA.CONCEPT_DIMENSION 
I2B2DEMODATA.VISIT_DIMENSION 
*/


CREATE TABLE TM_CZ.A_NCATS_DEMOGRAPHICS 
   (	C_HLEVEL NUMBER(22,0), 
	C_FULLNAME VARCHAR2(4000) NOT NULL ENABLE, 
	C_NAME VARCHAR2(4000), 
	C_SYNONYM_CD CHAR(1), 
	C_VISUALATTRIBUTES VARCHAR2(10), 
	C_TOTALNUM NUMBER(22,0), 
	C_BASECODE VARCHAR2(50), 
	C_METADATAXML CLOB, 
	C_FACTTABLECOLUMN VARCHAR2(50), 
	C_TABLENAME VARCHAR2(50), 
	C_COLUMNNAME VARCHAR2(50), 
	C_COLUMNDATATYPE VARCHAR2(50), 
	C_OPERATOR VARCHAR2(10), 
	C_DIMCODE VARCHAR2(4000), 
	C_COMMENT CLOB, 
	C_TOOLTIP VARCHAR2(4000), 
	UPDATE_DATE DATE NOT NULL ENABLE, 
	DOWNLOAD_DATE DATE, 
	IMPORT_DATE DATE, 
	SOURCESYSTEM_CD VARCHAR2(50), 
	VALUETYPE_CD VARCHAR2(50), 
	M_APPLIED_PATH VARCHAR2(700), 
	M_EXCLUSION_CD VARCHAR2(25), 
	C_PATH VARCHAR2(4000), 
	C_SYMBOL VARCHAR2(50)
   ) ;
   
-- @data_insert_ncats_demographics.sql
    
CREATE TABLE  TM_CZ.A_NCATS_VISIT_DETAILS 
   (	C_HLEVEL NUMBER(22,0), 
	C_FULLNAME VARCHAR2(4000) NOT NULL ENABLE, 
	C_NAME VARCHAR2(4000), 
	C_SYNONYM_CD CHAR(1), 
	C_VISUALATTRIBUTES VARCHAR2(10), 
	C_TOTALNUM NUMBER(22,0), 
	C_BASECODE VARCHAR2(50), 
	C_METADATAXML CLOB, 
	C_FACTTABLECOLUMN VARCHAR2(50), 
	C_TABLENAME VARCHAR2(50), 
	C_COLUMNNAME VARCHAR2(50), 
	C_COLUMNDATATYPE VARCHAR2(50), 
	C_OPERATOR VARCHAR2(10), 
	C_DIMCODE VARCHAR2(4000), 
	C_COMMENT CLOB, 
	C_TOOLTIP VARCHAR2(4000), 
	UPDATE_DATE DATE NOT NULL ENABLE, 
	DOWNLOAD_DATE DATE, 
	IMPORT_DATE DATE, 
	SOURCESYSTEM_CD VARCHAR2(50), 
	VALUETYPE_CD VARCHAR2(50), 
	M_APPLIED_PATH VARCHAR2(700), 
	M_EXCLUSION_CD VARCHAR2(25), 
	C_PATH VARCHAR2(4000), 
	C_SYMBOL VARCHAR2(50)
   ) ;
-- @data_insert_metadata_visits_oracle_V201.sql  


CREATE TABLE TM_CZ.A_ACT_ICD10PCS_PX_2018AA_MAP 
   (	BCH_CONCEPT_PATH VARCHAR2(4000), 
	BCH_CONCEPT_CD VARCHAR2(50), 
	BCH_NAME_CHAR VARCHAR2(2000), 
	ACT_CONCEPT_PATH VARCHAR2(4000), 
	ACT_CONCEPT_CD VARCHAR2(50), 
	ACT_NAME_CHAR VARCHAR2(4000)
   ) ;
   
-- data_A_ACT_ICD10PCS_PX_2018AA_MAP.tar.gz ( csv file for to load in  TM_CZ.A_ACT_ICD10PCS_PX_2018AA_MAP)

CREATE TABLE TM_CZ.A_NCATS_ICD10_ICD9_DX_V1_MAP 
   (	BCH_CONCEPT_PATH VARCHAR2(4000), 
	BCH_CONCEPT_CD VARCHAR2(50), 
	BCH_NAME_CHAR VARCHAR2(2000), 
	ACT_CONCEPT_PATH VARCHAR2(4000), 
	ACT_CONCEPT_CD VARCHAR2(50), 
	ACT_NAME_CHAR VARCHAR2(4000)
   ) ;
-- data_A_NCATS_ICD10_ICD9_DX_V1_MAP.tar.gz ( csv file for to load in  TM_CZ.A_NCATS_ICD10_ICD9_DX_V1_MAP )


CREATE TABLE TM_CZ.HPDS_DATA_LATEST 
   (	PATIENT_NUM NUMBER, 
	CONCEPT_PATH VARCHAR2(4000 ), 
	NVAL_NUM NUMBER, 
	TVAL_CHAR VARCHAR2(4000 ),
        START_DATE date
   )  ;
